/**
 * @videoedit/timeline-schema — shared timeline contract.
 * Time math, easing reference implementation, zod schemas and document-wide
 * invariants. JSON Schema for the C# side is generated by scripts/generate.ts.
 */

export * from './time.js';
export * from './easing.js';
export * from './schema.js';
export * from './invariants.js';

import { TimelineDocSchema } from './schema.js';
import { checkTimelineInvariants, type AssetDurations } from './invariants.js';

/**
 * Structural schema + document-wide invariants. Pass `assetDurations`
 * (assetId -> duration in us) to additionally enforce source-range bounds and
 * the transition D/2 handle rule; without it those checks are skipped.
 */
export function createTimelineDocSchema(assetDurations?: AssetDurations) {
  return TimelineDocSchema.superRefine((doc, ctx) => checkTimelineInvariants(doc, ctx, assetDurations));
}

/** Validate an unknown value as a TimelineDoc (structure + invariants). */
export function validateTimelineDoc(doc: unknown, assetDurations?: AssetDurations) {
  return createTimelineDocSchema(assetDurations).safeParse(doc);
}
